<?php

namespace AMAPBundle\Repository\Actualites;

/**
 * actualitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class actualitesRepository extends \Doctrine\ORM\EntityRepository
{
}
