<?php

namespace AMAPBundle\Repository;

/**
 * AccountSupplyManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountSupplyManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
