<?php

namespace AMAPBundle\Repository;

/**
 * AccountStoreManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountStoreManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
