<?php

namespace AMAPBundle\Repository;

/**
 * AccountAdministratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountAdministratorRepository extends \Doctrine\ORM\EntityRepository
{
}
