<?php

namespace AMAPBundle\Repository;

/**
 * AccountConsumerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountConsumerRepository extends \Doctrine\ORM\EntityRepository
{
}
