<?php

namespace AMAPBundle\Repository;

/**
 * AccountProducerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountProducerRepository extends \Doctrine\ORM\EntityRepository
{
}
