<?php

namespace AMAPBundle\Repository;

/**
 * DeliveryTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
