## YAML Template.
# src/AppBundle/Resources/config/admin.yml

services:
    # sonata
    admin.post:
        class: AMAPBundle\Admin\PostAdmin
        arguments: [~, AMAPBundle\Entity\Announcement\News, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "News", label: "News", label_catalogue: "AMAPBundle"}
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    admin.user:
        class: AMAPBundle\Admin\UserAdmin
        arguments: [~, AMAPBundle\Entity\Account\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "User", label_catalogue: "AMAPBundle"}
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    admin.group:
        class: AMAPBundle\Admin\GroupAdmin
        arguments: [~, AMAPBundle\Entity\Account\Group, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "Group", label_catalogue: "AMAPBundle"}
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    admin.amap:
        class: AMAPBundle\Admin\AMAPAdmin
        arguments: [~, AMAPBundle\Entity\AMAP\AMAP, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "AMAP", label: "AMAP", label_catalogue: "AMAPBundle" }
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    admin.basket:
        class: AMAPBundle\Admin\BasketAdmin
        arguments: [~, AMAPBundle\Entity\Basket\Basket, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Basket", label: "Basket", label_catalogue: "AMAPBundle" }
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    admin.product:
        class: AMAPBundle\Admin\ProductAdmin
        arguments: [~, AMAPBundle\Entity\Basket\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Basket", label: "Product", label_catalogue: "AMAPBundle" }
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    admin.contract:
        class: AMAPBundle\Admin\ContractAdmin
        arguments: [~, AMAPBundle\Entity\Contract\Contract, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "Contract", label_catalogue: "AMAPBundle" }
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
