## YAML Template.
# src/AppBundle/Resources/config/admin.yml

services:
    app.admin.post:
        class: AMAPBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - AMAPBundle\Entity\Sonata\BlogPost
            - ~
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
