## YAML Template.
# src/AppBundle/Resources/config/admin.yml

services:
    # sonata
    admin.news:
        class: AMAPBundle\Admin\NewsAdmin
        arguments: [~, AMAPBundle\Entity\Announcement\News, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "label_news", label: "label_news", label_catalogue: "AMAPBundle"}
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    admin.user:
        class: AMAPBundle\Admin\UserAdmin
        arguments: [~, AMAPBundle\Entity\Account\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "label_users", label: "label_user", label_catalogue: "AMAPBundle"}
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    admin.group:
        class: AMAPBundle\Admin\GroupAdmin
        arguments: [~, AMAPBundle\Entity\Account\Group, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "label_users", label: "label_group", label_catalogue: "AMAPBundle"}
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    admin.amap:
        class: AMAPBundle\Admin\AMAPAdmin
        arguments: [~, AMAPBundle\Entity\AMAP\AMAP, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "label_amap", label: "label_amap", label_catalogue: "AMAPBundle" }
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    admin.basket:
        class: AMAPBundle\Admin\BasketAdmin
        arguments: [~, AMAPBundle\Entity\Basket\Basket, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "label_basket", label: "label_basket", label_catalogue: "AMAPBundle" }
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    admin.product:
        class: AMAPBundle\Admin\ProductAdmin
        arguments: [~, AMAPBundle\Entity\Basket\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "label_basket", label: "label_product", label_catalogue: "AMAPBundle" }
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    admin.contract:
        class: AMAPBundle\Admin\ContractAdmin
        arguments: [~, AMAPBundle\Entity\Contract\Contract, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "label_users", label: "label_contract", label_catalogue: "AMAPBundle" }
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
