imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AMAPBundle/Resources/config/services.yml" }
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: "fr_FR"
    sonata.user.admin.user.entity: AMAPBundle\Entity\Account\User
    sonata.user.admin.group.entity: AMAPBundle\Entity\Account\Group
    sonata.user.admin.user.class: AMAPBundle\Admin\UserAdmin
framework:
    #esi:             ~
    translator:       
        fallback: [%locale%]  
        paths:
            - '%kernel.root_dir%/../src/AMAPBundle/Resources/translations'
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    #sonata
    form_themes:
        #- 'SonataCoreBundle:Form:datepicker.html.twig'
        - 'SonataFormatterBundle:Form:formatter.html.twig'
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
#fos user /group
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AMAPBundle\Entity\Account\User
    group:
        group_class: AMAPBundle\Entity\Account\Group
    registration:
        form:
            type: AMAPBundle\Form\UserType
        confirmation:
            enabled: true
            from_email:
                address:        "%mailer_user%"
                sender_name:    Confirm Registration
    resetting:
        email:
            from_email:
                address:        "%mailer_user%"
                sender_name:    Confirm Resetting
    service:
        mailer:               fos_user.mailer.twig_swift
        email_canonicalizer:  fos_user.util.canonicalizer.default
        token_generator:      fos_user.util.token_generator.default
        username_canonicalizer:  fos_user.util.canonicalizer.default
        user_manager:         fos_user.user_manager.default
# knp menu
knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig
# sonata
sonata_core:
    form_type: horizontal
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list: 
            contexts:   [admin]
        sonata.block.service.text: ~
        #search menu
        sonata.admin.block.search_result:
            contexts: [admin]
sonata_doctrine_orm_admin:
    # default value is null, so doctrine uses the value defined in the configuration
    entity_manager: ~
    audit:
        force: true
    templates:
        form:
            - SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig
        filter:
            - SonataDoctrineORMAdminBundle:Form:filter_admin_fields.html.twig
        types:
            list:
                array:      SonataAdminBundle:CRUD:list_array.html.twig
                boolean:    SonataAdminBundle:CRUD:list_boolean.html.twig
                date:       SonataAdminBundle:CRUD:list_date.html.twig
                time:       SonataAdminBundle:CRUD:list_time.html.twig
                datetime:   SonataAdminBundle:CRUD:list_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_list_field.html.twig
                trans:      SonataAdminBundle:CRUD:list_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_list_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_list_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_list_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_list_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_list_field.html.twig
                identifier: SonataAdminBundle:CRUD:base_list_field.html.twig
                currency:   SonataAdminBundle:CRUD:list_currency.html.twig
                percent:    SonataAdminBundle:CRUD:list_percent.html.twig
                choice:     SonataAdminBundle:CRUD:list_choice.html.twig
                url:        SonataAdminBundle:CRUD:list_url.html.twig

            show:
                array:      SonataAdminBundle:CRUD:show_array.html.twig
                boolean:    SonataAdminBundle:CRUD:show_boolean.html.twig
                date:       SonataAdminBundle:CRUD:show_date.html.twig
                time:       SonataAdminBundle:CRUD:show_time.html.twig
                datetime:   SonataAdminBundle:CRUD:show_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_show_field.html.twig
                trans:      SonataAdminBundle:CRUD:show_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_show_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_show_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_show_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_show_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_show_field.html.twig
                currency:   SonataAdminBundle:CRUD:base_currency.html.twig
                percent:    SonataAdminBundle:CRUD:base_percent.html.twig
                choice:     SonataAdminBundle:CRUD:show_choice.html.twig
                url:        SonataAdminBundle:CRUD:show_url.html.twig
sonata_formatter:
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig #keep this commented unless you are using media bundle.


        text:
            service: sonata.formatter.text.text
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        rawhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig


        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig
        twig:
            service: sonata.formatter.text.twigengine
            extensions: [] # Twig formatter cannot have extensions
    ckeditor:
        templates:
            browser: 'SonataFormatterBundle:Ckeditor:browser.html.twig'
            upload: 'SonataFormatterBundle:Ckeditor:upload.html.twig'
sonata_admin:
    title:      ISMA
    title_logo: images/logo/web_amap.ico
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig
        layout: AMAPBundle:Admin:menu.html.twig
    security:
        # the default value
        handler: sonata.admin.security.handler.role
    dashboard:
        blocks:
            # display a dashboard block
            - { position: top, type: sonata.block.service.text,class: col-md-10 col-md-offset-1, settings: {content: "<div align=\"center\"><h2>Bienvenue sur le panneau d'administration du site AMAPPlanet'</h2></div><p>L'outil d'administration du projet <code>ISMA</code> vous permet d'administrer le contenu des pages du site web <code>AMAPPlanet'</code>.</p> <br />" }}
            - { position: top, type: sonata.admin.block.admin_list,class: col-md-10 col-md-offset-1,settings: {groups:[amap.admin.group.user,amap.admin.group.news,amap.admin.group.amap,amap.admin.group.basket,amap.admin.group.delivery]}}
        groups:
            amap.admin.group.news:
                label_catalogue: AMAPBundle
                label: label_news
                icon: "<i class=\"fa fa-newspaper-o\"></i>"
                items:
                    - amap.admin.news
            amap.admin.group.user:
                label_catalogue: AMAPBundle
                label: label_users
                icon: "<i class=\"fa fa-users\"></i>"
                items:
                    - amap.admin.user
                    - amap.admin.group
                    - amap.admin.contract
            amap.admin.group.amap:
                label_catalogue: AMAPBundle
                label: label_amap
                icon: "<i class=\"fa fa-cutlery\"></i>"
                items:
                    - amap.admin.amap
            amap.admin.group.basket:
                label_catalogue: AMAPBundle
                label: label_basket
                icon: "<i class=\"fa fa-shopping-basket\"></i>"
                items:
                    - amap.admin.basket
                    - amap.admin.product
            amap.admin.group.delivery:
                label_catalogue: AMAPBundle
                label: label_delivery
                icon: "<i class=\"fa fa-building\"></i>"
                items:
                    - amap.admin.store
                    - amap.admin.warehouse