# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    
    role_hierarchy:
        ROLE_AUTOR:               [ROLE_USER]
        # Role producteur
        ROLE_AMAP_MANAGER:        [ROLE_ADMIN]
        # Role producteur
        ROLE_STORE_MANAGER:       [ROLE_ADMIN]
        # Role producteur
        ROLE_WAREHOUSE_MANAGER:   [ROLE_ADMIN]
        # Role producteur
        ROLE_CONSUMER:    [ROLE_AUTOR]
        # Role producteur
        ROLE_FARMER:      [ROLE_AUTOR]
        # Un admin hérite des droits d'auteur et de modérateur
        ROLE_ADMIN:       [ROLE_MODERATOR, ROLE_ALLOWED_TO_SWITCH, ROLE_SONATA_ADMIN,ROLE_FARMER,ROLE_CONSUMER]
        # On garde ce rôle superadmin, il nous resservira par la suite
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_WAREHOUSE_MANAGER,ROLE_STORE_MANAGER,ROLE_AMAP_MANAGER]
            
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username 	
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
            pattern: ^/
            logout: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: amap.redirect.after.login
            logout:
                path:   logout
                target: /accueil
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/responsable_amap, role: ROLE_AMAP_MANAGER }
        - { path: ^/responsable_entrepot, role: ROLE_WAREHOUSE_MANAGER }
        - { path: ^/responsable_magasin, role: ROLE_STORE_MANAGER }
        - { path: ^/utilisateur_producteur, role: ROLE_FARMER }
        - { path: ^/utilisateur_consommateur, role: ROLE_CONSUMER }
        - { path: ^/admin, role: ROLE_ADMIN }

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
