# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
services:
    # sonata
    admin.category:
        class: AMAPBundle\Admin\PostAdmin
        arguments: [~, AMAPBundle\Entity\Sonata\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
