amap_farmer_produit:
    path:     /monAMAP
    defaults: { _controller: AMAPBundle:Farmer:myamap }  
# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
# app/config/routing.yml
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
