# src/AppBundle/Resources/config/admin.yml
# sonata
services:
#    amap.example:
#        class: AMAPBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
## YAML Template.
#sonata admin
    amap.admin.news:
        class: AMAPBundle\Admin\NewsAdmin
        arguments: [~, AMAPBundle\Entity\Announcement\News, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "label_news"}
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    amap.admin.user:
        class: AMAPBundle\Admin\UserAdmin
        arguments: [~, AMAPBundle\Entity\Account\User, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "label_user"}
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    amap.admin.group:
        class: AMAPBundle\Admin\GroupAdmin
        arguments: [~, AMAPBundle\Entity\Account\Group, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "label_group"}
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    amap.admin.contract:
        class: AMAPBundle\Admin\ContractAdmin
        arguments: [~, AMAPBundle\Entity\Account\Contract, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "label_contract" }
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    amap.admin.amap:
        class: AMAPBundle\Admin\AMAPAdmin
        arguments: [~, AMAPBundle\Entity\AMAP\AMAP, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "label_amap"}
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    amap.admin.basket:
        class: AMAPBundle\Admin\BasketAdmin
        arguments: [~, AMAPBundle\Entity\Basket\Basket,  SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "label_basket"}
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
    amap.admin.product:
        class: AMAPBundle\Admin\ProductAdmin
        arguments: [~, AMAPBundle\Entity\Basket\Product, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "label_product" }
        calls:
            - [ setTranslationDomain, [AMAPBundle]]
            - [ setLabelTranslatorStrategy, [ "@sonata.admin.label.strategy.underscore" ]]
#login
    amap.security.interactive_login_listener:
        class: AMAPBundle\EventListener\UserLocaleListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: setLocaleForAuthenticatedUser }
    amap.security.kernel_request_listener:
        class: AMAPBundle\EventListener\UserLocaleListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: setLocaleForUnauthenticatedUser }
    amap.redirect.after.login:
        class: AMAPBundle\EventListener\AfterLoginRedirection
        arguments: ["@router"]
#twig
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }


