<?php

namespace AMAPBundle\Repository\LocalStoreManager;

/**
 * InfosStoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfosStoreRepository extends \Doctrine\ORM\EntityRepository
{
}
