<?php

namespace AMAPBundle\Repository\LocalStoreManager;

/**
 * StoreInfosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreInfosRepository extends \Doctrine\ORM\EntityRepository
{
}
