<?php

namespace AMAPBundle\Repository\AMAP;

/**
 * AMAPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AMAPRepository extends \Doctrine\ORM\EntityRepository
{
}
