<?php

namespace AMAPBundle\Repository\SupplyManager;

/**
 * WarehouseInfosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarehouseInfosRepository extends \Doctrine\ORM\EntityRepository
{
}
