<?php

namespace AMAPBundle\Repository\AmapManager;

/**
 * AccountAMAPManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountAMAPManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
