<?php

namespace AMAPBundle\Repository\Buying;

/**
 * CashPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CashPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
