<?php

namespace AMAPBundle\Repository\Buying;

/**
 * InternetPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternetPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
