<?php

namespace AMAPBundle\Repository\Farmer;

/**
 * AccountFarmerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountFarmerRepository extends \Doctrine\ORM\EntityRepository
{
}
