<?php

namespace AMAPBundle\Repository\Farmer;

/**
 * StatsConsumerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsConsumerRepository extends \Doctrine\ORM\EntityRepository
{
}
